# Generated by Django 5.2.5 on 2025-08-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
