# Generated by Django 5.2.5 on 2025-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0007_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
