# Generated by Django 5.2.5 on 2025-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0008_postreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='pending_review', max_length=20),
        ),
    ]
