# Generated by Django 5.2.5 on 2025-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0010_postreport_handled_by_admin_user_identity_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('victim', 'Victim'), ('witness', 'Witness'), ('perpetrator', 'Perpetrator'), ('journalist', 'Journalist'), ('activist', 'Activist'), ('official', 'Official'), ('other', 'Other')], max_length=20),
        ),
    ]
