# Generated by Django 5.2.5 on 2025-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0013_user_ban_reason_user_banned_at_user_banned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
