# Generated by Django 5.2.5 on 2025-08-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0014_alter_verificationrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_bans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Ban',
                'verbose_name_plural': 'IP Bans',
                'ordering': ['-banned_at'],
            },
        ),
    ]
