# Generated by Django 5.2.5 on 2025-08-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0015_ipban'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('role_change', 'Role Change'), ('post_status', 'Post Status Change'), ('post_deleted', 'Post Deleted'), ('report_handled', 'Report Handled'), ('verification_handled', 'Verification Handled'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_deleted', 'User Deleted'), ('person_deleted', 'Person Deleted')], max_length=50),
        ),
    ]
