# Generated by Django 5.2.5 on 2025-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0016_auditlog_description_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='posts', to='archive_app.person'),
        ),
    ]
