# Generated by Django 5.2.5 on 2025-08-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0018_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('role_change', 'Role Change'), ('post_status', 'Post Status Change'), ('post_deleted', 'Post Deleted'), ('report_handled', 'Report Handled'), ('verification_handled', 'Verification Handled'), ('user_banned', 'User Banned'), ('user_unbanned', 'User Unbanned'), ('user_deleted', 'User Deleted'), ('person_deleted', 'Person Deleted'), ('person_status_change', 'Person Status Change'), ('person_role_change', 'Person Role Change'), ('event_status_change', 'Event Status Change')], max_length=50),
        ),
    ]
