# Generated by Django 5.2.5 on 2025-08-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0019_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
