# Generated by Django 5.2.5 on 2025-08-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0020_remove_comment_image_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intended_role',
            field=models.CharField(blank=True, choices=[('journalist', 'Journalist'), ('politician', 'Politician')], help_text='Role requested during UID upload', max_length=20, null=True),
        ),
    ]
